import { Suspense } from "react";
import { useSuspenseQuery, queryOptions, QueryErrorResetBoundary } from "@tanstack/react-query";
import { ErrorBoundary } from "react-error-boundary";
import { Link, useNavigate } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { Building2, Users, Sparkles, UserCheck, Network, GraduationCap, RefreshCw, ArrowUpRight, Bell, Target, History, Globe2, Search } from "lucide-react";
import { format } from "date-fns";
import { fr } from "date-fns/locale";
import { StatCard } from "@/components/StatCard";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend } from "recharts";
import { PERIODS, type PilotagePeriod } from "@/lib/pilotage";
import { getPilotage } from "@/lib/pilotage.functions";
import { useActiveTemple } from "@/hooks/use-active-temple";

export type PilotageSearch = { period: PilotagePeriod; scope: string; q: string };

export function PilotageDashboard({ search }: { search: PilotageSearch }) {
  return <QueryErrorResetBoundary>{({ reset }) => <ErrorBoundary onReset={reset} resetKeys={[search.period,search.scope]} fallbackRender={({ resetErrorBoundary }) => <div role="alert" className="space-y-3 rounded-lg border border-destructive/30 bg-destructive/5 p-6"><h2 className="font-semibold">Impossible de charger le Centre de Pilotage MCA</h2><p className="text-sm text-muted-foreground">Les données ne sont pas disponibles pour le moment. Aucun chiffre n’a été remplacé par zéro.</p><Button onClick={resetErrorBoundary}><RefreshCw className="mr-2 h-4 w-4"/>Réessayer</Button></div>}><Suspense fallback={<div role="status" className="space-y-4"><h1 className="text-2xl font-bold">CENTRE DE PILOTAGE MCA</h1><p className="text-muted-foreground">Chargement des données autorisées…</p><div className="grid grid-cols-2 gap-4 lg:grid-cols-3">{Array.from({length:6},(_,i)=><div key={i} className="h-32 animate-pulse rounded-lg bg-muted"/>)}</div></div>}><PilotageContent search={search}/></Suspense></ErrorBoundary>}</QueryErrorResetBoundary>;
}

function PilotageContent({ search }: { search: PilotageSearch }) {
  const fetchPilotage = useServerFn(getPilotage);
  const options = queryOptions({queryKey:["pilotage",search.period,search.scope],queryFn:()=>fetchPilotage({data:{period:search.period,scope:search.scope}}),staleTime:60000,retry:1});
  const { data, refetch, isFetching, isRefetchError } = useSuspenseQuery(options);
  const navigate = useNavigate();
  const { setActiveTempleId } = useActiveTemple();
  const update = (value:Partial<PilotageSearch>) => navigate({to:"/dashboard",search:prev=>({...prev,...value})});
  const scopeLabel = search.scope === "global" ? "MCA GLOBAL" : search.scope.startsWith("country:") ? search.scope.slice(8) : data.temples[0]?.nom_temple ?? "—";
  const delta = (value:number|null,unit="") => value === null ? "Comparaison non disponible" : `${value>0?"+":""}${value}${unit} vs période précédente`;
  const filtered = data.temples.filter(t=>`${t.nom_temple} ${t.pays ?? ""}`.toLocaleLowerCase("fr").includes(search.q.toLocaleLowerCase("fr")));
  const selectTemple = (id:string) => { setActiveTempleId(id); void update({scope:id,q:""}); };
  const alerts = [
    {label:"Demandes de validation",value:data.alerts.requests,to:"/demandes"},
    {label:"Rapports de cultes en brouillon",value:data.alerts.reports,to:"/rapports"},
    {label:"Activités en retard",value:data.alerts.lateActivities,to:"/departements"},
    {label:"Absences aux 3 derniers cultes de la période",value:data.alerts.repeatedAbsences,to:"/alertes"},
  ];
  return <div className="min-w-0 space-y-8">
    <section className="space-y-4 border-b pb-6">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div className="min-w-0"><div className="mb-2 flex items-center gap-2 text-sm font-semibold text-primary"><Globe2 className="h-4 w-4"/>{scopeLabel}</div><h1 className="text-2xl font-bold lg:text-3xl">CENTRE DE PILOTAGE MCA</h1><p className="mt-2 text-sm text-muted-foreground">{format(new Date(data.bounds.start),"dd MMM yyyy",{locale:fr})} — {format(new Date(data.bounds.end),"dd MMM yyyy",{locale:fr})}</p></div>
        <div className="flex flex-wrap items-center gap-2"><Select value={search.period} onValueChange={value=>void update({period:value as PilotagePeriod})}><SelectTrigger aria-label="Période" className="w-44"><SelectValue/></SelectTrigger><SelectContent>{PERIODS.map(p=><SelectItem key={p.value} value={p.value}>{p.label}</SelectItem>)}</SelectContent></Select><Button aria-label="Actualiser le centre de pilotage" title="Actualiser" variant="outline" size="icon" disabled={isFetching} onClick={()=>void refetch()}><RefreshCw className={`h-4 w-4 ${isFetching?"animate-spin":""}`}/></Button></div>
      </div>
      <div className="flex flex-wrap items-center justify-between gap-2"><p className="text-xs text-muted-foreground">Dernière actualisation : {format(new Date(data.updatedAt),"dd/MM/yyyy HH:mm:ss",{locale:fr})}</p>{search.scope!=="global" && <Button variant="ghost" size="sm" onClick={()=>void update({scope:"global",q:""})}><Globe2 className="mr-2 h-4 w-4"/>Revenir à MCA GLOBAL</Button>}</div>
      {isRefetchError && <p role="alert" className="text-sm text-destructive">Actualisation échouée. Les chiffres affichés datent de la dernière actualisation réussie. <Button variant="link" onClick={()=>void refetch()}>Réessayer</Button></p>}
    </section>
    <section className="grid min-w-0 gap-4 sm:grid-cols-2 xl:grid-cols-3">
      <StatCard label="Temples enregistrés" value={data.stats.temples} hint={`${data.stats.activeTemples} actifs · périmètre consulté`} icon={Building2}/>
      <StatCard label="Membres inscrits" value={data.stats.members} hint={`${data.stats.activeMembers} actifs · ${data.stats.newMembers} inscriptions sur la période`} icon={Users}/>
      <StatCard label="Nouvelles âmes · période" value={data.stats.souls} hint={delta(data.stats.soulsDelta)} icon={Sparkles} variant="gold"/>
      <StatCard label="Taux de présence · période" value={data.stats.presence.rate===null?"—":`${data.stats.presence.rate}%`} hint={`${data.stats.presence.present} pointages présents · ${data.stats.services} cultes · ${delta(data.stats.presenceDelta," points")}`} icon={UserCheck} variant="success"/>
      <StatCard label="Départements actifs" value={data.stats.departments} hint="État actuel · périmètre consulté" icon={Network}/>
      <StatCard label="Membres en formation" value={data.stats.training} hint="Inscrits ou en cours · programmes actifs" icon={GraduationCap}/>
    </section>
    <section className="min-w-0 border-b pb-6"><h2 className="mb-1 text-lg font-semibold">Évolution des indicateurs</h2><p className="mb-5 text-xs text-muted-foreground">Inscriptions enregistrées, nouvelles âmes actuellement classées et pointages de présence. L’effectif historique total n’est pas disponible.</p>{data.chart.length ? <div className="h-72 min-w-0 w-full"><ResponsiveContainer width="100%" height="100%"><LineChart data={data.chart} margin={{top:10,right:12,left:-20,bottom:0}}><CartesianGrid strokeDasharray="3 3" stroke="var(--border)"/><XAxis dataKey="date" tickFormatter={d=>format(new Date(d),"dd/MM")} stroke="var(--muted-foreground)" fontSize={11} minTickGap={28}/><YAxis stroke="var(--muted-foreground)" fontSize={11} allowDecimals={false}/><Tooltip labelFormatter={d=>format(new Date(String(d)),"dd MMM yyyy",{locale:fr})} contentStyle={{background:"var(--card)",border:"1px solid var(--border)",borderRadius:8}}/><Legend wrapperStyle={{fontSize:12}}/><Line type="linear" dataKey="presents" name="Pointages présents" stroke="var(--primary)" strokeWidth={2} dot={false}/><Line type="linear" dataKey="inscriptions" name="Inscriptions" stroke="var(--success)" strokeWidth={2} dot={false}/><Line type="linear" dataKey="nouvelles" name="Nouvelles âmes" stroke="var(--gold)" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer></div> : <p className="py-8 text-sm text-muted-foreground">Aucune inscription ni aucun culte enregistré sur cette période. Aucun historique d’effectif n’est reconstitué.</p>}</section>
    {(search.scope==="global" || search.scope.startsWith("country:")) && <section className="space-y-4 border-b pb-6"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold">État des temples</h2><div className="relative w-full sm:w-64"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input aria-label="Rechercher un temple" placeholder="Rechercher un temple…" className="pl-9" value={search.q} onChange={e=>void update({q:e.target.value})}/></div></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(t=><article key={t.id} className="min-w-0 rounded-lg border bg-card p-4"><div className="flex items-start justify-between gap-2"><h3 className="break-words font-semibold">{t.nom_temple}</h3><Button aria-label={`Consulter ${t.nom_temple}`} title="Consulter ce temple" variant="ghost" size="icon" className="shrink-0" onClick={()=>selectTemple(t.id)}><ArrowUpRight className="h-4 w-4"/></Button></div><p className="mb-4 text-xs text-muted-foreground">{t.pays ?? "Pays non renseigné"} · {t.actif?"Actif":"Inactif"}</p><dl className="grid grid-cols-2 gap-3 text-sm"><div><dt className="text-xs text-muted-foreground">Membres inscrits</dt><dd className="font-semibold">{t.members} <span className="text-xs font-normal text-muted-foreground">({t.activeMembers} actifs)</span></dd></div><div><dt className="text-xs text-muted-foreground">Présence · période</dt><dd className="font-semibold">{t.presence===null?"—":`${t.presence}%`}</dd></div><div><dt className="text-xs text-muted-foreground">Activités · période</dt><dd>{t.activities}</dd></div><div><dt className="text-xs text-muted-foreground">Rapports validés</dt><dd>{t.totalReports?`${t.reports} / ${t.totalReports}`:"—"}</dd></div></dl></article>)}</div>{!filtered.length && <p className="text-sm text-muted-foreground">Aucun temple dans ce périmètre ou pour cette recherche.</p>}</section>}
    <section className="grid gap-8 xl:grid-cols-2">
      <div className="min-w-0"><div className="mb-4 flex items-center justify-between gap-2"><h2 className="flex items-center gap-2 text-lg font-semibold"><Bell className="h-5 w-5 text-gold"/>Alertes et validations</h2><Link to="/alertes" className="text-xs font-medium text-primary">Alertes <ArrowUpRight className="inline h-3 w-3"/></Link></div><div className="divide-y">{alerts.map(a=><Link key={a.to} to={a.to} className="flex items-center justify-between gap-3 py-3 text-sm"><span>{a.label}</span><Badge variant={a.value?"default":"secondary"}>{a.value}</Badge></Link>)}{data.alerts.finance.map(f=><Link key={f.op} to={f.op==="mission_offering"?"/finances/missions":"/finances/cotisations"} className="flex items-center justify-between gap-3 py-3 text-sm"><span>{f.op==="mission_offering"?"Offrandes missionnaires":"Cotisations sociales"}<span className="block text-xs text-muted-foreground">Reliquats dont la date prévue est dépassée</span></span><Badge variant={f.count?"default":"secondary"}>{f.count}</Badge></Link>)}</div><p className="mt-2 text-xs text-muted-foreground">Activités en retard : état actuel. Les autres indicateurs suivent la période sélectionnée.</p></div>
      <div className="min-w-0"><div className="mb-4 flex items-center justify-between gap-2"><h2 className="flex items-center gap-2 text-lg font-semibold"><Target className="h-5 w-5 text-primary"/>Progression des objectifs MCA</h2><Link to="/objectifs" className="text-xs font-medium text-primary">Objectifs <ArrowUpRight className="inline h-3 w-3"/></Link></div><p className="mb-3 text-xs text-muted-foreground">Objectifs annuels {data.bounds.year} · progression au {format(new Date(data.bounds.end),"dd/MM/yyyy")}</p>{!data.objectives.length && <p className="py-6 text-sm text-muted-foreground">Aucun objectif enregistré pour {data.bounds.year} dans ce périmètre.</p>}<div className="space-y-5">{data.objectives.map(o=><div key={o.id}><div className="flex flex-wrap justify-between gap-2 text-sm"><span className="font-medium">{o.label}</span><Badge variant="secondary">{o.rate===null?"Non disponible":o.rate>=100?"Atteint":"En cours"}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{o.temple} · {o.actual===null?"—":o.actual.toLocaleString("fr-FR")} / {o.target.toLocaleString("fr-FR")} · {o.rate===null?"—":`${o.rate}%`}</p>{o.rate!==null && <Progress value={Math.min(100,Math.max(0,o.rate))} className="mt-2 h-2"/>}</div>)}</div></div>
    </section>
    <section className="border-t pt-6"><div className="mb-4 flex items-center justify-between"><h2 className="flex items-center gap-2 text-lg font-semibold"><History className="h-5 w-5 text-primary"/>Activité récente</h2><Link to="/historique" className="text-xs font-medium text-primary">Historique <ArrowUpRight className="inline h-3 w-3"/></Link></div>{!data.recent.length && <p className="text-sm text-muted-foreground">Aucune action rattachée à ce périmètre sur la période sélectionnée.</p>}<div className="divide-y">{data.recent.map(r=><div key={r.id} className="grid gap-1 py-3 text-sm sm:grid-cols-[140px_1fr_1fr]"><time className="text-xs text-muted-foreground">{format(new Date(r.date),"dd/MM/yyyy HH:mm")}</time><div><p className="break-words font-medium">{r.action}</p><p className="text-xs text-muted-foreground">{r.user}</p></div><p className="break-words text-xs text-muted-foreground">{r.temple}</p></div>)}</div></section>
  </div>;
}