/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWhatsappRouteImport } from './routes/_app/whatsapp'
import { Route as AppUtilisateursRouteImport } from './routes/_app/utilisateurs'
import { Route as AppTemplesRouteImport } from './routes/_app/temples'
import { Route as AppRapportsRouteImport } from './routes/_app/rapports'
import { Route as AppParametresRouteImport } from './routes/_app/parametres'
import { Route as AppObjectifsRouteImport } from './routes/_app/objectifs'
import { Route as AppFormationsRouteImport } from './routes/_app/formations'
import { Route as AppMembresRouteImport } from './routes/_app/membres'
import { Route as AppHistoriqueRouteImport } from './routes/_app/historique'
import { Route as AppFormationsRouteImport } from './routes/_app/formations'
import { Route as AppFinancesRouteImport } from './routes/_app/finances'
import { Route as AppExportsRouteImport } from './routes/_app/exports'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCultesRouteImport } from './routes/_app/cultes'
import { Route as AppActivitesRouteImport } from './routes/_app/activites'
import { Route as AppPresencesIndexRouteImport } from './routes/_app/presences.index'
import { Route as AppPresencesCulteIdRouteImport } from './routes/_app/presences.$culteId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppUtilisateursRoute = AppUtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplesRoute = AppTemplesRouteImport.update({
  id: '/temples',
  path: '/temples',
  getParentRoute: () => AppRoute,
} as any)
const AppRapportsRoute = AppRapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => AppRoute,
} as any)
const AppParametresRoute = AppParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AppRoute,
} as any)
const AppObjectifsRoute = AppObjectifsRouteImport.update({
  id: '/objectifs',
  path: '/objectifs',
  getParentRoute: () => AppRoute,
} as any)
const AppFormationsRoute = AppFormationsRouteImport.update({
  id: '/formations',
  path: '/formations',
  getParentRoute: () => AppRoute,
} as any)
const AppMembresRoute = AppMembresRouteImport.update({
  id: '/membres',
  path: '/membres',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoriqueRoute = AppHistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => AppRoute,
} as any)
const AppFormationsRoute = AppFormationsRouteImport.update({
  id: '/formations',
  path: '/formations',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancesRoute = AppFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => AppRoute,
} as any)
const AppExportsRoute = AppExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCultesRoute = AppCultesRouteImport.update({
  id: '/cultes',
  path: '/cultes',
  getParentRoute: () => AppRoute,
} as any)
const AppActivitesRoute = AppActivitesRouteImport.update({
  id: '/activites',
  path: '/activites',
  getParentRoute: () => AppRoute,
} as any)
const AppPresencesIndexRoute = AppPresencesIndexRouteImport.update({
  id: '/presences/',
  path: '/presences/',
  getParentRoute: () => AppRoute,
} as any)
const AppPresencesCulteIdRoute = AppPresencesCulteIdRouteImport.update({
  id: '/presences/$culteId',
  path: '/presences/$culteId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/activites': typeof AppActivitesRoute
  '/cultes': typeof AppCultesRoute
  '/dashboard': typeof AppDashboardRoute
  '/exports': typeof AppExportsRoute
  '/finances': typeof AppFinancesRoute
  '/formations': typeof AppFormationsRoute
  '/historique': typeof AppHistoriqueRoute
  '/membres': typeof AppMembresRoute
  '/objectifs': typeof AppObjectifsRoute
  '/formations': typeof AppFormationsRoute
  '/parametres': typeof AppParametresRoute
  '/rapports': typeof AppRapportsRoute
  '/temples': typeof AppTemplesRoute
  '/utilisateurs': typeof AppUtilisateursRoute
  '/whatsapp': typeof AppWhatsappRoute
  '/presences/$culteId': typeof AppPresencesCulteIdRoute
  '/presences/': typeof AppPresencesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/activites': typeof AppActivitesRoute
  '/cultes': typeof AppCultesRoute
  '/dashboard': typeof AppDashboardRoute
  '/exports': typeof AppExportsRoute
  '/finances': typeof AppFinancesRoute
  '/formations': typeof AppFormationsRoute
  '/historique': typeof AppHistoriqueRoute
  '/membres': typeof AppMembresRoute
  '/objectifs': typeof AppObjectifsRoute
  '/formations': typeof AppFormationsRoute
  '/parametres': typeof AppParametresRoute
  '/rapports': typeof AppRapportsRoute
  '/temples': typeof AppTemplesRoute
  '/utilisateurs': typeof AppUtilisateursRoute
  '/whatsapp': typeof AppWhatsappRoute
  '/presences/$culteId': typeof AppPresencesCulteIdRoute
  '/presences': typeof AppPresencesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_app/activites': typeof AppActivitesRoute
  '/_app/cultes': typeof AppCultesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/exports': typeof AppExportsRoute
  '/_app/finances': typeof AppFinancesRoute
  '/_app/formations': typeof AppFormationsRoute
  '/_app/historique': typeof AppHistoriqueRoute
  '/_app/membres': typeof AppMembresRoute
  '/_app/objectifs': typeof AppObjectifsRoute
  '/_app/formations': typeof AppFormationsRoute
  '/_app/parametres': typeof AppParametresRoute
  '/_app/rapports': typeof AppRapportsRoute
  '/_app/temples': typeof AppTemplesRoute
  '/_app/utilisateurs': typeof AppUtilisateursRoute
  '/_app/whatsapp': typeof AppWhatsappRoute
  '/_app/presences/$culteId': typeof AppPresencesCulteIdRoute
  '/_app/presences/': typeof AppPresencesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/activites'
    | '/cultes'
    | '/dashboard'
    | '/exports'
    | '/finances'
    | '/formations'
    | '/historique'
    | '/membres'
    | '/objectifs'
    | '/formations'
    | '/parametres'
    | '/rapports'
    | '/temples'
    | '/utilisateurs'
    | '/whatsapp'
    | '/presences/$culteId'
    | '/presences/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/activites'
    | '/cultes'
    | '/dashboard'
    | '/exports'
    | '/finances'
    | '/formations'
    | '/historique'
    | '/membres'
    | '/objectifs'
    | '/formations'
    | '/parametres'
    | '/rapports'
    | '/temples'
    | '/utilisateurs'
    | '/whatsapp'
    | '/presences/$culteId'
    | '/presences'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_app/activites'
    | '/_app/cultes'
    | '/_app/dashboard'
    | '/_app/exports'
    | '/_app/finances'
    | '/_app/formations'
    | '/_app/historique'
    | '/_app/membres'
    | '/_app/objectifs'
    | '/_app/formations'
    | '/_app/parametres'
    | '/_app/rapports'
    | '/_app/temples'
    | '/_app/utilisateurs'
    | '/_app/whatsapp'
    | '/_app/presences/$culteId'
    | '/_app/presences/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/whatsapp': {
      id: '/_app/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/utilisateurs': {
      id: '/_app/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/utilisateurs'
      preLoaderRoute: typeof AppUtilisateursRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/temples': {
      id: '/_app/temples'
      path: '/temples'
      fullPath: '/temples'
      preLoaderRoute: typeof AppTemplesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rapports': {
      id: '/_app/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof AppRapportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parametres': {
      id: '/_app/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AppParametresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/objectifs': {
      id: '/_app/objectifs'
      path: '/objectifs'
      fullPath: '/objectifs'
      preLoaderRoute: typeof AppObjectifsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/formations': {
      id: '/_app/formations'
      path: '/formations'
      fullPath: '/formations'
      preLoaderRoute: typeof AppFormationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/membres': {
      id: '/_app/membres'
      path: '/membres'
      fullPath: '/membres'
      preLoaderRoute: typeof AppMembresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/historique': {
      id: '/_app/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof AppHistoriqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/formations': {
      id: '/_app/formations'
      path: '/formations'
      fullPath: '/formations'
      preLoaderRoute: typeof AppFormationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finances': {
      id: '/_app/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof AppFinancesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exports': {
      id: '/_app/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof AppExportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cultes': {
      id: '/_app/cultes'
      path: '/cultes'
      fullPath: '/cultes'
      preLoaderRoute: typeof AppCultesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activites': {
      id: '/_app/activites'
      path: '/activites'
      fullPath: '/activites'
      preLoaderRoute: typeof AppActivitesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/presences/': {
      id: '/_app/presences/'
      path: '/presences'
      fullPath: '/presences/'
      preLoaderRoute: typeof AppPresencesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/presences/$culteId': {
      id: '/_app/presences/$culteId'
      path: '/presences/$culteId'
      fullPath: '/presences/$culteId'
      preLoaderRoute: typeof AppPresencesCulteIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivitesRoute: typeof AppActivitesRoute
  AppCultesRoute: typeof AppCultesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExportsRoute: typeof AppExportsRoute
  AppFinancesRoute: typeof AppFinancesRoute
  AppFormationsRoute: typeof AppFormationsRoute
  AppHistoriqueRoute: typeof AppHistoriqueRoute
  AppMembresRoute: typeof AppMembresRoute
  AppObjectifsRoute: typeof AppObjectifsRoute
  AppFormationsRoute: typeof AppFormationsRoute
  AppParametresRoute: typeof AppParametresRoute
  AppRapportsRoute: typeof AppRapportsRoute
  AppTemplesRoute: typeof AppTemplesRoute
  AppUtilisateursRoute: typeof AppUtilisateursRoute
  AppWhatsappRoute: typeof AppWhatsappRoute
  AppPresencesCulteIdRoute: typeof AppPresencesCulteIdRoute
  AppPresencesIndexRoute: typeof AppPresencesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivitesRoute: AppActivitesRoute,
  AppCultesRoute: AppCultesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExportsRoute: AppExportsRoute,
  AppFinancesRoute: AppFinancesRoute,
  AppFormationsRoute: AppFormationsRoute,
  AppHistoriqueRoute: AppHistoriqueRoute,
  AppMembresRoute: AppMembresRoute,
  AppObjectifsRoute: AppObjectifsRoute,
  AppFormationsRoute: AppFormationsRoute,
  AppParametresRoute: AppParametresRoute,
  AppRapportsRoute: AppRapportsRoute,
  AppTemplesRoute: AppTemplesRoute,
  AppUtilisateursRoute: AppUtilisateursRoute,
  AppWhatsappRoute: AppWhatsappRoute,
  AppPresencesCulteIdRoute: AppPresencesCulteIdRoute,
  AppPresencesIndexRoute: AppPresencesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
