
ALTER TABLE public.membres
  ADD COLUMN IF NOT EXISTS email TEXT,
  ADD COLUMN IF NOT EXISTS date_entree DATE;

ALTER TABLE public.cultes
  ADD COLUMN IF NOT EXISTS offrandes NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS dimes NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS depenses NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS solde_caisse NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS notes_finances TEXT;
